### Create a new book
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Lord of The Rings",
  "author": "J.R.R. Tolkienn"
}

### Get all books
GET http://localhost:8080/books

### Get book by ID (replace 1 with actual ID)
GET http://localhost:8080/books/10010

### Get books by author name (exact match, URL-encoded if needed)
GET http://localhost:8080/books/author/J.R.R.%20Tolkienn

### Get books by title (exact match, URL-encoded if needed)
GET http://localhost:8080/books/title/Lord%20of%20The%20Rings

### Update book by ID (replace 1 with actual ID)
PUT http://localhost:8080/books/10009
Content-Type: application/json

{
  "title": "The Hobbitt",
  "author": "J.R.R. Tolkien"
}

### Delete book by ID (replace 1 with actual ID)
DELETE http://localhost:8080/books/10004
